version: '3' 
services: 
  instalment: 
    build: 
      context: . 
    ports: 
      - "3000:3000"
    command: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

